const queList = [
  "Quẻ 1: Mọi việc hanh thông, nhưng nhớ hanh thôi, đừng thông quá kẻo đau đầu.",
  "Quẻ 2: Gia đình ấm êm, nhưng thỉnh thoảng vẫn tranh cãi vì ai rửa chén.",
  "Quẻ 3: Công danh sự nghiệp thăng tiến, nhưng cẩn thận, thăng quá dễ trượt chân!",
  "Quẻ 4: Sức khỏe dồi dào, tinh thần minh mẫn, nhưng đừng ăn khuya nhiều quá, bụng dồi luôn!",
  "Quẻ 5: Tình duyên nở rộ, nhưng nhớ tưới nước thường xuyên kẻo héo.",
  "Quẻ 6: Cẩn trọng trong việc đầu tư, đừng mua quá nhiều mì gói khi giảm giá.",
  "Quẻ 7: Gặp được quý nhân phù trợ, nhưng nhớ xin số điện thoại để còn liên lạc.",
  "Quẻ 8: Học hành tấn tới, nhưng đừng quên ngủ, kẻo tấn tới bệnh viện!",
  "Quẻ 9: Nên giữ bình tĩnh, đừng nổi nóng khi wifi chậm, kẻo tốn tiền sửa router.",
  "Quẻ 10: Thành công đến từ sự kiên nhẫn, nhưng đừng chờ lâu quá, deadline không chờ ai!",
  "Quẻ 11: Gia đình hòa thuận, trừ khi bàn chuyện ăn gì tối nay.",
  "Quẻ 12: Tình cảm lứa đôi ngày càng khăng khít, nhưng nhớ khít vừa thôi, đừng bóp nghẹt nhau!",
  "Quẻ 13: Mọi khó khăn đều sẽ vượt qua, trừ việc giải bài toán cấp 3.",
  "Quẻ 14: Cơ hội mới đang đến, nhưng nhớ mở cửa ra chào đón.",
  "Quẻ 15: Công việc tiến triển tốt đẹp, nhưng đừng quên làm báo cáo cho sếp!",
  "Quẻ 16: Đầu tư khôn ngoan, nhưng đừng đầu tư vào việc ngủ quá nhiều.",
  "Quẻ 17: Mọi thứ sẽ trở nên dễ dàng nếu bạn làm việc chăm chỉ, nhưng đừng chăm chỉ đến mức quên ăn.",
  "Quẻ 18: Chúc bạn luôn gặp may mắn trong cuộc sống, trừ khi bạn đổ xe vào chỗ đỗ xe của người khác.",
  "Quẻ 19: Mọi mối quan hệ đều tốt đẹp, tình yêu đong đầy, nhưng đừng yêu... chiếc điều khiển TV.",
  "Quẻ 20: Tình hình tài chính ổn định, bạn sẽ không lo lắng về tiền bạc, trừ khi mua sắm quá đà.",
  "Quẻ 21: Bạn sẽ tìm được sự nghiệp yêu thích và phát triển tốt, nhưng nhớ đừng quên thời gian nghỉ ngơi.",
  "Quẻ 22: Công việc đạt kết quả cao nhờ sự cố gắng và sáng tạo, nhưng sáng tạo quá có thể khiến bạn bị lạc đường.",
  "Quẻ 23: Tình yêu hạnh phúc, sự nghiệp vững vàng, nhưng đừng quên yêu cả chính bản thân mình.",
  "Quẻ 24: Chúc bạn vượt qua mọi thử thách để đạt được ước mơ, nhưng đừng thử thách sức chịu đựng của bạn bè.",
  "Quẻ 25: Mọi kế hoạch sẽ thành công mỹ mãn, trừ khi bạn quên mang theo tài liệu quan trọng.",
  "Quẻ 26: Chúc bạn tìm được niềm vui trong công việc mỗi ngày, nhưng đừng tìm niềm vui trong việc lười biếng.",
  "Quẻ 27: Hãy luôn tin tưởng vào bản thân, thành công sẽ đến, nhưng đừng tin vào bản thân quá mức khi chơi game.",
  "Quẻ 28: Gia đình bạn sẽ đón nhận nhiều niềm vui bất ngờ, nhưng đừng bất ngờ quá khi thấy hóa đơn điện thoại.",
  "Quẻ 29: Cơ hội thăng tiến trong công việc đang đến gần, nhưng đừng thăng tiến quá nhanh kẻo bị chóng mặt.",
  "Quẻ 30: Tình cảm gia đình sẽ ngày càng gắn bó hơn, nhưng đừng gắn bó quá, kẻo không có không gian riêng.",
  "Quẻ 31: Hãy làm việc hết mình, thành công sẽ không xa, nhưng đừng làm hết mình đến mức quên ngủ.",

  "Quẻ 32: Cả nhà cùng nhau vượt khó, kiểu như cả nhà cùng nhau... đóng tiền phạt ấy mà.",
  "Quẻ 33: Mục tiêu lớn sẽ đạt được, miễn là mục tiêu đó không phải là... bay lên trời.",
  "Quẻ 34: Tài chính cải thiện, có khi đủ tiền mua... mì tôm hảo hạng mỗi ngày.",
  "Quẻ 35: Tình yêu và sự nghiệp song hành, ví dụ như... yêu sếp chẳng hạn.",
  "Quẻ 36: Đừng ngại thử thách, nhưng nhớ... mang theo phao cứu sinh.",
  "Quẻ 37: Mọi mối quan hệ đều hòa thuận, trừ... mấy đứa bạn hay đòi nợ.",
  "Quẻ 38: Cơ hội du lịch, có thể là... đi quanh xóm bằng xe đạp.",
  "Quẻ 39: Tiếp tục nỗ lực, nhưng nhớ... nghỉ ngơi kẻo tẩu hỏa nhập ma.",
  "Quẻ 40: Hạnh phúc đến khi biết chia sẻ, ví dụ như... chia sẻ wifi chẳng hạn.",
  "Quẻ 41: Đường tình duyên ngọt ngào, cẩn thận... sâu răng.",
  "Quẻ 42: Sự nghiệp thăng tiến, có khi lên chức... chạy việc vặt.",
  "Quẻ 43: Cả nhà đón tin vui, có thể là... trúng xổ số kiến thiết.",
  "Quẻ 44: Sống tích cực, nhưng đừng... ảo tưởng sức mạnh.",
  "Quẻ 45: Công việc ổn định, tức là... vẫn làm công việc cũ.",
  "Quẻ 46: Tình yêu đơm hoa kết trái, có khi là... cưới nhau xong rồi có em bé.",
  "Quẻ 47: Được công nhận trong công việc, ví dụ như... được khen là chăm chỉ.",
  "Quẻ 48: Tin vào bản thân, nhưng đừng... tự tin thái quá.",
  "Quẻ 49: Sức khỏe cải thiện, có khi hết... sổ mũi.",
  "Quẻ 50: Công việc tiến triển, có thể được... đổi ghế ngồi mới.",
  "Quẻ 51: Một năm nhiều niềm vui, nhưng nhớ... đề phòng tháng cô hồn.",
  "Quẻ 52: Gia đình hạnh phúc, miễn là... đừng ai giành nhau remote TV.",
  "Quẻ 53: Đừng sợ thất bại, nhưng cũng đừng... thất bại quá nhiều lần.",
  "Quẻ 54: Tài lộc đến từ dự định, nhưng nhớ... tính toán kỹ kẻo lỗ.",
  "Quẻ 55: Tình yêu thăng hoa, công việc thuận lợi, cẩn thận... bị người ta ghen tị.",
  "Quẻ 56: Vượt qua khó khăn, nhưng đừng... tự tạo thêm khó khăn.",
  "Quẻ 57: Gặp gỡ người quan trọng, có khi là... gặp được idol trên mạng.",
  "Quẻ 58: Công việc ổn định và vui vẻ, nhưng nhớ... đừng có ngủ gật ở chỗ làm.",
  "Quẻ 59: Theo đuổi ước mơ, nhưng nhớ... phải thực tế.",
  "Quẻ 60: Tình cảm gia đình tràn đầy yêu thương, nhưng nhớ... đừng có cãi nhau vì chuyện vặt.",
  "Quẻ 61: Tập trung vào mục tiêu, nhưng nhớ... đừng bỏ bê sức khỏe.",
  "Quẻ 62: Nhận điều tốt đẹp trong công việc, có khi là... được ăn liên hoan.",
  "Quẻ 63: Cùng nhau vượt thử thách, nhưng nhớ... chia việc ra chứ đừng để một người làm hết.",
  "Quẻ 64: Tình yêu ngọt ngào, gia đình ấm êm, cẩn thận... bị người ngoài ghen tị.",
  "Quẻ 65: Chăm chỉ làm việc, kết quả tuyệt vời, nhưng nhớ... đừng làm quá sức.",
  "Quẻ 66: Sự nghiệp phát triển mạnh mẽ, nhưng nhớ... giữ gìn sức khỏe.",
  "Quẻ 67: Đừng bỏ cuộc, nhưng cũng đừng... cố chấp.",
  "Quẻ 68: Tình yêu và công việc song hành, ví dụ như... yêu đồng nghiệp.",
  "Quẻ 69: Mọi việc thuận lợi, nhưng nhớ... vẫn phải cẩn thận.",
  "Quẻ 70: Tìm niềm vui trong điều nhỏ nhặt, ví dụ như... ăn được món mình thích.",
  "Quẻ 71: Sự nghiệp có bước tiến lớn, có khi được... chuyển sang phòng máy lạnh.",
  "Quẻ 72: Gia đình hạnh phúc và bình yên, nhưng nhớ... đừng có gây gỗ với hàng xóm.",
  "Quẻ 73: Khó khăn qua đi, nhưng nhớ... rút kinh nghiệm.",
  "Quẻ 74: Cơ hội mới đến, nhưng nhớ... phải nắm bắt chứ đừng để nó trôi qua.",
  "Quẻ 75: Nhận giúp đỡ từ người thân, nhưng nhớ... phải biết ơn.",
  "Quẻ 76: Tình cảm gia đình đong đầy, nhưng nhớ... đừng có quên gọi điện cho bố mẹ.",
  "Quẻ 77: Gặp bạn tốt, nhưng nhớ... đừng có lợi dụng họ.",
  "Quẻ 78: Mọi việc như mong muốn, nhưng nhớ... đừng có chủ quan.",
  "Quẻ 79: Tìm thấy bình yên trong tâm hồn, nhưng nhớ... đừng có trốn tránh thực tại.",
  "Quẻ 80: Quyết định dẫn đến kết quả tốt, nhưng nhớ... phải suy nghĩ kỹ trước khi quyết định.",
  "Quẻ 81: Gia đình đoàn kết và yêu thương, nhưng nhớ... đừng có chia bè kết phái.",
  "Quẻ 82: Sống tích cực, gặp may mắn, nhưng nhớ... đừng có trông chờ vào vận may.",
  "Quẻ 83: Công việc có cơ hội thăng tiến, nhưng nhớ... phải nỗ lực chứ không phải chỉ chờ đợi.",
  "Quẻ 84: Tình duyên nở rộ, gặp người phù hợp, nhưng nhớ... phải tìm hiểu kỹ trước khi tiến xa.",
  "Quẻ 85: Giữ tinh thần lạc quan, nhưng nhớ... đừng có lạc quan tếu.",
  "Quẻ 86: Luôn hạnh phúc và thành công, nhưng nhớ... đừng có tự mãn.",
  "Quẻ 87: Cơ hội phát triển đến, nhưng nhớ... phải chuẩn bị sẵn sàng.",
  "Quẻ 88: Mọi mong muốn thành hiện thực, nhưng nhớ... phải biết ước mơ.",
  "Quẻ 89: Tình yêu mang lại an lành, nhưng nhớ... đừng có mù quáng.",
  "Quẻ 90: Công việc tiến triển tích cực, nhưng nhớ... vẫn phải cố gắng.",
  "Quẻ 91: Đừng lo lắng về tương lai, nhưng nhớ... vẫn phải có kế hoạch.",
  "Quẻ 92: Gặp quý nhân giúp đỡ, nhưng nhớ... phải biết tự lực.",
  "Quẻ 93: Thành công lớn trong sự nghiệp, nhưng nhớ... đừng có kiêu ngạo.",
  "Quẻ 94: Gia đình yêu thương và quan tâm, nhưng nhớ... cũng phải dành thời gian cho nhau.",
  "Quẻ 95: Tình yêu ngày càng thắm thiết, nhưng nhớ... phải luôn vun đắp.",
  "Quẻ 96: Luôn tin vào chính mình, nhưng nhớ... phải biết lắng nghe.",
  "Quẻ 97: Mọi việc đều mang lại kết quả tốt, nhưng nhớ... phải làm việc có tâm.",
  "Quẻ 98: Cơ hội tài chính đến gần, nhưng nhớ... phải tỉnh táo.",
  "Quẻ 99: Sức khỏe và tinh thần được duy trì, nhưng nhớ... vẫn phải chăm sóc bản thân.",
  "Quẻ 100: Công việc đem lại niềm vui, nhưng nhớ... đừng có quên gia đình.",
  "Quẻ 101: Mọi sự suôn sẻ nếu kiên nhẫn và chăm chỉ, nhưng nhớ... đừng có lười biếng.",
  "Quẻ 102: Gặp nhiều cơ hội phát triển, nhưng nhớ... phải biết lựa chọn.",
  "Quẻ 103: Tình yêu và gia đình là động lực, nhưng nhớ... cũng phải tự tạo động lực cho mình.",
  "Quẻ 104: Nhận đánh giá cao từ mọi người, nhưng nhớ... đừng có ảo tưởng.",
  "Quẻ 105: Sự nghiệp luôn thăng tiến, nhưng nhớ... phải khiêm tốn.",
  "Quẻ 106: Tình cảm gia đình tràn ngập niềm vui, nhưng nhớ... phải biết trân trọng",
  "Quẻ 107: Bạn sẽ gặp được những người đáng tin cậy trong công việc.",
  "Quẻ 108: Hãy luôn mạnh mẽ, mọi điều tốt đẹp sẽ đến với bạn.",
  "Quẻ 109: Tài lộc và sự nghiệp sẽ phát triển mạnh mẽ.",
  "Quẻ 110: Bạn sẽ tìm thấy sự bình an trong tâm hồn.",
];

function gieoQue() {
  const randomIndex = Math.floor(Math.random() * queList.length);
  const resultText = document.getElementById("result-text");
  const resultDiv = document.getElementById("result");
  resultText.textContent = queList[randomIndex];
  resultDiv.style.display = "block";
}
